name: Basic-Schulung
on:
  push:
  workflow-dispatch:
  
jobs:
  build:
    name: my first action
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - uses: ./action-a
        with: 
          MY_NAME: Oliver    
